name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65db0441e524c5b62e2b5c56d7960f1138a9bb2e3b42ef2f015d334e2786febb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
