name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55f51b5ab5ba85bbae8ad3a10913c372b588c0cc43120fe1f6a5aded31aaee1d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
