name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e94587eca8546eb5c2df668b8d1e63b87afa2adb61148bbd1c2b1e894adbca9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
