name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f38b0ad680d0c8d53580b18afc08fe7f5c45a4824b6209a32017cb89e558c8d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
