name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c49d513c327c203127a2631522019d199c4b5490f27ddcfb3af0d25ba70dbbda"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
