name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffc99f16543624434532674ab7bf9b3181962bfe740c88ca77d6665d566f8bd7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
