name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10523b4c010ff73c50afd4626df0cdc28d42610c0a8a70b38602b04f860d6a1a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
