name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cd147c543943ecbd071dec9807ee7dadb9efee64853332c02ca5106cec6d84f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
